services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
    depends_on:
      - db
    restart: on-failure
  db:
    image: mongo:8.0-noble
    volumes:
      - ./mongo:/data/db