services:
  jupyter:
    image: codeurjc/analisis-partidos-futbol-influxdb
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=MY_SECRET
      - INFLUXDB_HOST=http://influxdb3:8181
      - INFLUXDB_DB=telemetry
    depends_on:
      - influxdb3
    restart: on-failure
  influxdb3:
    image: influxdb:3-core
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
      - --without-auth
    volumes:
      - db_data:/var/lib/influxdb3

volumes:
  db_data:
