services:
  telemetry-analyzer:
    build: .
    environment:
      - JUPYTER_TOKEN=MY_SECRET
      - INFLUXDB_HOST=http://influxdb3:8181
      - INFLUXDB_DB=telemetry
    depends_on:
      influxdb3:
        condition: service_healthy
    volumes:
      - ./output:/project/output
  influxdb3:
    image: influxdb:3-core
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --without-auth
    volumes:
      - ./influxdb3_data:/var/lib/influxdb3/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
